name: Python Package Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [published]

jobs:
  test:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest tests

  build-and-publish:
    needs: test
    runs-on: ubuntu-latest
    # Only run on main branch or when a release is published
    if: github.event_name == 'release' || github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install uv
      run: |
        pip install uv

    - name: Create virtual environment
      run: |
        uv venv
        . .venv/bin/activate

    - name: Install build dependencies
      run: |
        uv pip install build twine

    - name: Build package
      run: |
        . .venv/bin/activate
        python -m build

    # Publish to PyPI only on release
    - name: Publish to PyPI
      if: github.event_name == 'release'
      run: |
        . .venv/bin/activate
        python -m twine upload dist/*
